### ISSUE TITLE
VM/VMX sometimes fails to unwind from __exp1 on ARM

### ISSUE THREAD

**Issue by Baraa-Hasheesh** [async-profiler/async-profiler#1408]
### Describe the bug

While testing #1405 to validate the full scope of the issue it was noticed when running the `StackwalkerTests.largeFrame` test that the stack walker fails to unwind from the `__exp1` method

This can be observed by simply running the test & checking the collected samples 

```
Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask 12
Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask;pow 7
Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask;pow;__ieee754_pow 52
Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask;pow;__ieee754_pow;__exp1 176
Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask;unknown;__ieee754_pow 2
Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask;__kernel_standard 25
Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask;__sqrt 2
Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask;pow@plt 1
Java_test_stackwalker_StackGenerator_largeFrame;unknown;__kernel_standard 2
Java_test_stackwalker_StackGenerator_largeFrame;__kernel_standard 1
__exp1 3
```

### Reproduction Steps

`make test TESTS=StackwalkerTests.largeFrame`

### Async-profiler version

latest

### Environment details

aarch64
AL2

**Comment by fandreuz** [comment]
Possibly dup of #1402 ?

**Comment by Baraa-Hasheesh** [comment]
@fandreuz could be the same problem manifesting on a different method, as I'm analyzing a different issue, I didn't look into this.

**Comment by fandreuz** [comment]
@Baraa-Hasheesh did you manage to check if this is the same issue?

**Comment by Baraa-Hasheesh** [comment]
@fandreuz I didn't look into this yet

**Comment by Baraa-Hasheesh** [comment]
@apangin while checking stacks across multiple systems I did observe that async events such as CPU & WALL have a higher error rate on the top frame

For example 
* Java_test_stackwalker_StackGenerator_largeFrame;doCpuTask;unknown;__ieee754_pow 
Fails to unwind correctly from **__ieee754_pow** to **doCpuTask**
* Java_test_stackwalker_StackGenerator_largeFrame;unknown;__kernel_standard
Fails to unwind correctly from **__kernel_standard** to **doCpuTask**
* Java_test_stackwalker_StackGenerator_largeFrame;__kernel_standard
Fully skips **doCpuTask**
* __exp1 
Fails to unwind to **doCpuTask**

I was thinking can't we create a recovery strategy for top frame using `frame.link`?

For example 
```
if (inDeadZone(pc) && depth <= 1) { // try to recover from link register if unwinding fails on first frame
     pc = (const void*)frame.link();
}
```

```
last_method = profiler->findNativeMethod(pc);
if (last_method == NULL && depth == 1) {
      pc = (const void*)frame.link();
      last_method = profiler->findNativeMethod(pc);
}
fillFrame(frames[depth++], BCI_NATIVE_FRAME, last_method);
```

```
/* Code to check if a frame was skipped between the top 2 frames using link register *
/* Can happen when unwinding for frameless frames */
```

would doing something along these thoughts be a valid recovery strategy?

**Comment by Baraa-Hasheesh** [comment]
@apangin I did some checks here & I believe the issue here is quite similar to the solved issue inside `StackFrame::unwindPrologue` 

```
000000000002f540 <__exp1>:
   2f540:	d10083ff 	sub	sp, sp, #0x20
   2f544:	90000481 	adrp	x1, bf000 <__FRAME_END__+0x14e44>
   2f548:	9e660004 	fmov	x4, d0
   2f54c:	52b86e00 	mov	w0, #0xc3700000            	// #-1016070144
   2f550:	52840026 	mov	w6, #0x2001                	// #8193
   2f554:	d2800005 	mov	x5, #0x0                   	// #0
   2f558:	a9017bfd 	stp	x29, x30, [sp, #16]
   2f55c:	910043fd 	add	x29, sp, #0x10
   2f560:	72a07ec6 	movk	w6, #0x3f6, lsl #16
```

The samples that fail to unwind correctly are captured before the SP is updated/stored, which causes the unwinding to be done incorrectly,

In other words it's very similar to prologue portion of StackFrame

**Comment by Baraa-Hasheesh** [comment]
Some additional information
Dwarf unwinding information exists & looks to be applied correctly 
* SP is adjusted by the 32 amount 

```
000045f8 0000000000000024 000045fc FDE cie=00000000 pc=000000000002f540..000000000002f870
   LOC           CFA      x29   ra    
000000000002f540 sp+0     u     u     
000000000002f544 sp+32    u     u     
000000000002f55c sp+32    c-16  c-8   
000000000002f560 x29+16   c-16  c-8   
000000000002f5ec sp+0     u     u     
000000000002f5f0 x29+16   c-16  c-8 
```

I tried some stuff in GDB
& The next pc in the chain is found at `prev_sp + 24` rather than `prev_sp + 32`
SP is the same between both profiler & gdb at the `__exp1` frame

`sp` on frame `__pow_finite` is correct for both,
I'm assuming the issue is in the pc_off

```
(gdb) p *((void**)(prev_sp + 32))
$22 = (void *) 0x3ff0000000000000
(gdb) p *((void**)(prev_sp + 24))
$23 = (void *) 0xfffff6869624 <__pow_finite+676>

(gdb) bt
#0  StackWalker::walkVM (ucontext=0xfffff6833b50, frames=0xfffff3858be0, max_depth=2048, detail=VM_EXPERT, pc=0x0, sp=281474817543504, fp=281474817543536) at src/stackWalker.cpp:447
#1  0x0000fffff6258fd4 in StackWalker::walkVM (ucontext=0xfffff6833b50, frames=0xfffff3858be0, max_depth=2048, detail=VM_EXPERT) at src/stackWalker.cpp:211
#2  0x0000fffff6249ef0 in Profiler::recordSample (this=0xfffff002bf40, ucontext=0xfffff6833b50, counter=10000000, event_type=EXECUTION_SAMPLE, event=0xfffff6833ab8) at src/profiler.cpp:654
#3  0x0000fffff622da3c in CpuEngine::signalHandler (signo=27, siginfo=0xfffff6833ad0, ucontext=0xfffff6833b50) at src/cpuEngine.cpp:120
#4  <signal handler called>
#5  0x0000fffff6866548 in __exp1 () from /lib64/libm.so.6
#6  0x0000fffff6869624 in __pow_finite () from /lib64/libm.so.6
#7  0x0000fffff6840258 in pow () from /lib64/libm.so.6
#8  0x0000fffff55ec950 in doCpuTask () from /workplace/bhashesh/async-profiler/build/test/lib/libjninativestacks.so
#9  0x0000fffff55eca38 in Java_test_stackwalker_StackGenerator_leafFrame () from /workplace/bhashesh/async-profiler/build/test/lib/libjninativestacks.so
#10 0x0000ffffdf92d1d8 in ?? ()
#11 0x0000ffffdf92aeb8 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

(gdb) p/x prev_sp
$1 = 0xfffff6834d30
(gdb) f 5
#5  0x0000fffff6866550 in __exp1 () from /lib64/libm.so.6
(gdb) p $sp
$2 = (void *) 0xfffff6834d30
(gdb) f 6
#6  0x0000fffff6869624 in __pow_finite () from /lib64/libm.so.6
(gdb) p $sp
$3 = (void *) 0xfffff6834d50
(gdb) f 0
#0  StackWalker::walkVM (ucontext=0xfffff6833b50, frames=0xfffff381cec0, max_depth=2048, detail=VM_EXPERT, pc=0x0, sp=281474817543504, fp=281474817543536) at src/stackWalker.cpp:447
447                 fprintf(stderr, "Problem %s\n", cc->name());
(gdb) p/x sp
$6 = 0xfffff6834d50

```

**Comment by Baraa-Hasheesh** [comment]
Managed to create a similar issue 

```
extern JNIEXPORT double doCpuTask2() {
    char frame[0x30000];
    // Prevent from being optimized by compiler
    (void)frame;
    return sqrt(10) + pow(1, 10);
}

extern JNIEXPORT double linker() {
    return doCpuTask2();
}


JNIEXPORT jdouble JNICALL Java_test_stackwalker_StackGenerator_reproduce(JNIEnv* env, jclass cls) {
    double result = 0;
    for (long long i = 0; i < 1000000000LL; ++i) {
        result += linker();
    }
    return result;
}
```

```
test/stackwalker/StackGenerator.main_[0];test/stackwalker/StackGenerator.reproduce_[0];Java_test_stackwalker_StackGenerator_reproduce 402
test/stackwalker/StackGenerator.main_[0];test/stackwalker/StackGenerator.reproduce_[0];Java_test_stackwalker_StackGenerator_reproduce;linker@plt 12
test/stackwalker/StackGenerator.main_[0];test/stackwalker/StackGenerator.reproduce_[0];Java_test_stackwalker_StackGenerator_reproduce;linker 20
test/stackwalker/StackGenerator.main_[0];test/stackwalker/StackGenerator.reproduce_[0];Java_test_stackwalker_StackGenerator_reproduce;linker;doCpuTask2@plt 10
test/stackwalker/StackGenerator.main_[0];test/stackwalker/StackGenerator.reproduce_[0];Java_test_stackwalker_StackGenerator_reproduce;linker;doCpuTask2 9
test/stackwalker/StackGenerator.main_[0];test/stackwalker/StackGenerator.reproduce_[0];Java_test_stackwalker_StackGenerator_reproduce;unknown;doCpuTask2 9
```

**test/stackwalker/StackGenerator.main_[0];test/stackwalker/StackGenerator.reproduce_[0];Java_test_stackwalker_StackGenerator_reproduce;unknown;doCpuTask2 11**

Explanation 

The sample happens at the following instruction which have the following unwind info 

```
[b44,b50] db

0000000000000b40 <doCpuTask2>:
 b40:	d140c3ff 	sub	sp, sp, #0x30, lsl #12
 b44:	90000000 	adrp	x0, 0 <_init-0x868>
 b48:	912f6000 	add	x0, x0, #0xbd8
 b4c:	fd400000 	ldr	d0, [x0]
 b50:	9140c3ff 	add	sp, sp, #0x30, lsl #12
 b54:	d65f03c0 	ret

00000160 0000000000000018 00000164 FDE cie=00000000 pc=0000000000000b40..0000000000000b58
   LOC           CFA      
0000000000000b40 sp+0     
0000000000000b44 sp+196608 
0000000000000b54 sp+0     
```

Whenever an instruction is sampled between 0xb44 & 0xb50 it will use `0000000000000b44 sp+196608` to unwind
However there is no valid return address available in the unwind info

In this case the user should profiler should use RA, however as CFA isn't 0 (196608), async-profiler will try to get the new PC by dereferencing the SP, which will return random values 

=> dwarf unwind should be modified to use RA on top frame if there are no valid return address information

**Comment by apangin** [comment]
Fixed in #1463

**Comment by fandreuz** [comment]
@apangin This issue is back in our macos-x64 GHA job, unfortunately: https://github.com/async-profiler/async-profiler/actions/runs/18000882526/job/51209713128#step:10:303

**Comment by Baraa-Hasheesh** [comment]
@fandreuz this is a different issue 
related to this https://github.com/async-profiler/async-profiler/issues/1418
