### ISSUE TITLE
Async in Docker with outside report file

### ISSUE THREAD

**Issue by ixplo** [async-profiler/async-profiler#353]
When we attach to a process inside a docker container, async saves the report file inside the container. Can you make it keep it outside?

**Comment by apangin** [comment]
Async-profiler works in the context of the target JVM process. When JVM runs in a container, profiler can access only what is accessible inside the container.

I'm investigating the possibility to stream profiling results through a socket for async-profiler 2.0. But so far if you want profiler to dump file onto the host system, you need to bind-mount a host path in the container.

**Comment by krk** [comment]
Closing as resolved by https://github.com/async-profiler/async-profiler/pull/411. Feel free to reopen or create a new ticket otherwise.

**Comment by apangin** [comment]
I believe this issue is still relevant.
#411 solves a different problem. This one is about treating `-f` argument as a host-relative path, whereas async-profiler currently saves profiles in a container filesystem, even when runned from a host.
