### ISSUE TITLE
Async Profiler and Java Flight Recorder are missing some methods at the bottom of the stack.

### ISSUE THREAD

**Issue by qsLI** [async-profiler/async-profiler#845]
From a code perspective, the correct call order should be： `Thread.run -> FastThreadLocalRunnable.run -> ThreadPoolExecutor$Worker.run -> ThreadPoolExecutor.runWorker`

✅using jstack:
<img width="1509" alt="image" src="https://github.com/async-profiler/async-profiler/assets/6805785/257db204-ede4-447e-89e3-2171f1db591c">

❌using async profiler:

<img width="425" alt="image" src="https://github.com/async-profiler/async-profiler/assets/6805785/12e90feb-1be4-41f3-b9be-946fdc7b9e33">

❌using jfr ExecutionSample event:
<img width="467" alt="image" src="https://github.com/async-profiler/async-profiler/assets/6805785/061cce51-aa49-4488-ad86-e4867d9d6bb9">

This doesn't seem to be a bug with async profiler, any thoughts?

**Comment by heifrank** [comment]
> Did you added DebugNonSafepoints as suggested in the readme?

@franz1981 If it's really DebugNonSafepoints problem, then jstack will also show missing stack frame, however jstack shows  correctly.

**Comment by franz1981** [comment]
Depends. If there is a safepoint poll within an inlined method, jstack can still observe (and blame it), while, without the option I've specified, both jfr and async profiler won't be able to do the same (loop striping can still add polls to counted loops).
Regarding your method: are you using CPU profiling? If yes, jstack has captured a WAITING thread which is not something a CPU profiler would show up, because...it doesn't consume CPU (unless in the precess of contending on some process futex to do it).

**Comment by apangin** [comment]
If it's not an async-profiler bug, will it be better to submit an OpenJDK issue instead?
If you could provide a reproducible example, I'd be happy to analyze that.
Btw, does the issue happen with other JDK versions or with a different CPU architecture?

**Comment by apangin** [comment]
How does `--cstack vm` work? Does it show missing frame?

**Comment by qsLI** [comment]
> How does `--cstack vm` work? Does it show missing frame?

jdk.ActiveSetting cstack value is fp when using --cstack vm，seems a bug？

https://github.com/async-profiler/async-profiler/blob/29b78f4670b58272ce5968774baed06381f8d0aa/src/flightRecorder.cpp#L71C1-L71C1

using command:
`./asprof   -e cpu --cstack vm -d 60 -f p.jfr  `

jfr info:
`jdk.ActiveSetting {
  startTime = 08:40:06.344
  id = 107
  name = "cstack"
  value = "fp"
  eventThread = "Attach Listener" (javaThreadId = 2700)
}`

**Comment by apangin** [comment]
> jdk.ActiveSetting cstack value is fp when using --cstack vm，seems a bug？

Yes, thank you for pointing out. I pushed the fix.

**Comment by qsLI** [comment]
> How does `--cstack vm` work? Does it show missing frame?

still not working with async-profiler-2.10-linux-x64 

cmd `./asprof   -e cpu --cstack vm -d 60 -f  p.html `

<img width="1435" alt="image" src="https://github.com/async-profiler/async-profiler/assets/6805785/89f85954-3190-4135-9c38-b6dddd93fcf0">

**Comment by apangin** [comment]
This does not look like a `vm` stack trace.
`cstack=vm` option appeared in async-profiler 3.0-ea.

**Comment by qsLI** [comment]
> This does not look like a `vm` stack trace. `cstack=vm` option appeared in async-profiler 3.0-ea.

- `cstack=vm` mode is correct

<img width="1789" alt="image" src="https://github.com/async-profiler/async-profiler/assets/6805785/81820df7-c3ab-40d7-b50c-c5b37b335965">

- the same host with `cstack=fp`

<img width="1691" alt="image" src="https://github.com/async-profiler/async-profiler/assets/6805785/d3d911e2-eb34-436b-8599-d588974f0f89">

**Comment by apangin** [comment]
Thank you for the update. Good to know async-profiler's own stack walker works correctly. It will eventually replace JVM's AsyncGetCallTrace and become the default.

**Comment by qsLI** [comment]
> Thank you for the update. Good to know async-profiler's own stack walker works correctly. It will eventually replace JVM's AsyncGetCallTrace and become the default.

`cstack=vm` reads the symbol information (gHotSpotVMStructs) exported by the JVM, then finds the offset related to PCDesc, reads the corresponding data, and obtains the call stack information. Since the vm mode is correct, it can be inferred that the information of PCDesc is correct or enough, which has nothing to do with DebugNonSafePoint?

**Comment by apangin** [comment]
Yes, `DebugNonSafepoints` option may affect accuracy of the topmost virtual frames, but not a frame at the bottom of the stack.

**Comment by apangin** [comment]
Let me close the issue, since there is nothing to do on async-profiler side.
